# Generated by Django 4.1 on 2022-10-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_categorysubscribers_remove_post_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorysubscribers',
            old_name='categoruy',
            new_name='category',
        ),
    ]
